plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

application {
    mainClass = 'ru.servicecenter.client.ServiceCenterApp'
}

javafx {
    version = '21.0.4'
    modules = ['javafx.controls', 'javafx.fxml']
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.2'

    compileOnly "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
}

tasks.named('jar') {
    manifest {
        attributes 'Main-Class': 'ru.servicecenter.client.ServiceCenterApp'
    }
}
